publish: dist

services:
  - type: static
    name: acsii-iragaki
    buildCommand: npm install && npm run build
    publishPath: dist
    env: static
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache
          - key: Access-Control-Allow-Origin
            value: "*"
          - key: Permissions-Policy
            value: "camera=self"
          - key: Feature-Policy
            value: "camera 'self'"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
