publish: dist

services:
  - type: static
    name: acsii-iragaki
    buildCommand: npm install && npm run build
    publishPath: dist
    staticPublishPath: ./dist
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
