publish: dist

services:
  - type: web
    name: acsii
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    env: static
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
